### ISSUE TITLE
설치란에 dependancy 올려주실 수 있으신가요?

### ISSUE THREAD

**Issue by songhune** [graykode/toeicbert#1]
pytorch가 필요한 것 같은데, 현재 RuntimeError: PyTorch does not currently provide packages for PyPI에러가 뜨고 있어요 ㅠㅠ

**Comment by graykode** [comment]
안녕하세요. https://github.com/graykode/toeicbert/blob/master/setup.py#L16의 `install_requires`에 torch 있습니다. 감사합니다.
